[package]
name = "hell0_cargo"
version = "0.1.0"
authors = ["lafest <lafest@minding.today>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"